<?php

namespace app\admin\controller;

use think\Lang;

class Snstrace extends AdminControl
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Lang::load(APP_PATH . 'admin/lang/'.config('default_lang').'/snstrace.lang.php');
    }

    /**
     * 动态列表
     */
    public function index()
    {
        $condition = array();
        //会员名
        if (input('param.search_uname') != '') {
            $condition['tracelog_membernamelike'] = trim(input('param.search_uname'));
        }
        //内容
        if (input('param.search_content') != '') {
            $condition['tracelog_contentortitle'] = trim(input('param.search_content'));
        }
        //状态
        if (input('param.search_state') != '') {
            $condition['tracelog_state'] = input('param.search_state');
        }
        //发表时间
        if (input('param.search_stime') != '') {
            $condition['stime'] = strtotime(input('param.search_stime'));
        }
        if (input('param.search_etime') != '') {
            $condition['etime'] = strtotime(input('param.search_etime'));
        }
        //分页
        
        $snstracelog_model = model('snstracelog');
        $tracelog_list = $snstracelog_model->getSnstracelogList($condition,10);
        if (!empty($tracelog_list)) {
            foreach ($tracelog_list as $k => $v) {
                if (!empty($v['tracelog_title'])) {
                    //替换标题中的siteurl
                    $v['tracelog_title'] = str_replace("%siteurl%", HOME_SITE_URL . DS, $v['tracelog_title']);
                }
                if (!empty($v['tracelog_content'])) {
                    //替换内容中的siteurl
                    $v['tracelog_content'] = str_replace("%siteurl%", HOME_SITE_URL . DS, $v['tracelog_content']);
                    //将收藏商品和店铺连接剔除
                    $v['tracelog_content'] = str_replace(lang('admin_snstrace_collectgoods'), "", $v['tracelog_content']);
                    $v['tracelog_content'] = str_replace(lang('admin_snstrace_collectstore'), "", $v['tracelog_content']);
                }
                $tracelog_list[$k] = $v;
            }
        }
        $this->setAdminCurItem('index');
        $this->assign('tracelog_list', $tracelog_list);
        $this->assign('show_page', $snstracelog_model->page_info->render());
        
        $this->assign('filtered', $condition ? 1 : 0); //是否有查询条件
        
        return $this->fetch();
    }

    /**
     * 删除动态
     */
    public function tracedel()
    {
        $tid = $_POST['t_id'];
        if (empty($tid)) {
            $this->error(lang('admin_snstrace_pleasechoose_del'), 'snstrace/index');
        }
        $tid_str = implode("','", $tid);
        //删除动态
        $snstracelog_model = model('snstracelog');
        $result = $snstracelog_model->delSnstracelog(array('tracelog_id_in' => $tid_str));
        if ($result) {
            //判断是否完全删除
            $tracelog_list = $snstracelog_model->getSnstracelogList(array('traceid_in' => "$tid_str"));
            if (!empty($tracelog_list)) {
                foreach ($tracelog_list as $k => $v) {
                    unset($tid[array_search($v['tracelog_id'], $tid)]);
                }
            }
            $tid_str = implode("','", $tid);
            //删除动态下的评论
            $snscomment_model = model('snscomment');
            $condition = array();
            $condition['snscomment_originalid'] = array('in',$tid_str);
            $condition['snscomment_originaltype'] = "0";
            $snscomment_model->delSnscomment($condition);
            //更新转帖的原帖删除状态为已经删除
            $snstracelog_model->editSnstracelog(array('tracelog_originalstate' => '1'), array('tracelog_originalid_in' => "$tid_str"));
            $this->log(lang('ds_del').lang('admin_snstrace_comment'), 1);
            $this->success(lang('ds_common_del_succ'), 'snstrace/index');
        }
        else {
            $this->error(lang('ds_common_del_fail'), 'snstrace/index');
        }
    }

    /**
     * 编辑动态
     */
    public function traceedit()
    {
        $tid = $_POST['t_id'];
        if (empty($tid)) {
            $this->error(lang('admin_snstrace_pleasechoose_edit'), 'snstrace/index');
        }
        $tid_str = implode("','", $tid);
        $type = input('param.type');
        //删除动态
        $snstracelog_model = model('snstracelog');
        $update_arr = array();
        if ($type == 'hide') {
            $update_arr['tracelog_state'] = '1';
        }
        else {
            $update_arr['tracelog_state'] = '0';
        }
        $result = $snstracelog_model->editSnstracelog($update_arr, array('traceid_in' => "$tid_str"));
        unset($update_arr);
        if ($result>=0) {
            //判断是否完全修改成功
            $condition = array();
            $condition['traceid_in'] = "$tid_str";
            if ($type == 'hide') {
                $condition['tracelog_state'] = '1';
            }else {
                $condition['tracelog_state'] = '0';
            }
            $tracelog_list = $snstracelog_model->getSnstracelogList($condition);
            unset($condition);
            $tid_new = array();
            if (!empty($tracelog_list)) {
                foreach ($tracelog_list as $k => $v) {
                    $tid_new[] = $v['tracelog_id'];
                }
            }
            $tid_str = implode("','", $tid_new);
            //更新转帖的原帖删除状态为已经删除或者为显示
            $update_arr = array();
            if ($type == 'hide') {
                $update_arr['tracelog_originalstate'] = '1';
            }else {
                $update_arr['tracelog_originalstate'] = '0';
            }
            $snstracelog_model->editSnstracelog($update_arr, array('tracelog_originalid_in' => "$tid_str"));
            $this->log(lang('ds_edit').lang('admin_snstrace_comment'), 1);
            $this->success(lang('ds_common_op_succ'), 'Snstrace/index');
        }
        else {
            $this->error(lang('ds_common_op_fail'), 'Snstrace/index');
        }
    }

    /**
     * 评论列表
     */
    public function commentlist()
    {
        $snscomment_model = model('snscomment');
        //查询评论总数
        $condition = array();
        //会员名
        if (input('param.search_uname') != '') {
            $condition['snscomment_membername'] = array('like', "%" . input('param.search_uname') . "%");
        }
        //内容
        if (input('param.search_content') != '') {
            $condition['snscomment_content'] = array('like', "%" . input('param.search_content') . "%");
        }
        //状态
        if (input('param.search_state') != '') {
            $condition['snscomment_state'] = input('param.search_state');
        }
        //发表时间
        if (input('param.search_stime') != '' && input('param.search_etime') != '') {
            $stime = strtotime(input('param.search_stime'));
            $etime = strtotime(input('param.search_etime'));
            $condition['snscomment_addtime'] = array('between', array($stime, $etime));
        }
        if (input('param.tid') != '') {
            $condition['snscomment_originalid'] = input('param.tid');
            $condition['snscomment_originaltype'] = "0";//原帖类型 0表示动态信息 1表示分享商品
        }
        //评价列表
        $commentlist = $snscomment_model->getSnscommentList($condition, 10);
        $this->assign('commentlist', $commentlist);
        $this->assign('show_page', $snscomment_model->page_info->render());
        
        $this->assign('filtered', $condition ? 1 : 0); //是否有查询条件
        
        $this->setAdminCurItem('commentlist');
        return $this->fetch();
    }

    /**
     * 删除评论
     */
    public function commentdel()
    {
        $cid = $_POST['c_id'];
        if (empty($cid)) {
            $this->error(lang('admin_snstrace_pleasechoose_del'), 'Snstrace/commentlist');
        }
        $cid_str = implode("','", $cid);
        //删除评论
        $snscomment_model = model('snscomment');
        $condition = array();
        $condition['snscomment_id'] = array('in',$cid_str);
        $result = $snscomment_model->delSnscomment($condition);
        if ($result) {
            $this->log(lang('ds_del').lang('admin_snstrace_pl'), 1);
            $this->success(lang('ds_common_del_succ'), 'Snstrace/commentlist');
        }
        else {
            $this->error(lang('ds_common_del_fail'), 'Snstrace/commentlist');
        }
    }

    /**
     * 编辑评论
     */
    public function commentedit()
    {
        $cid = $_POST['c_id'];
        if (empty($cid)) {
            $this->error(lang('admin_snstrace_pleasechoose_edit'), 'snstrace/commentlist');
        }
        $cid_str = implode("','", $cid);
        $type = input('param.type');
        //删除动态
        $snscomment_model = model('snscomment');
        $update_arr = array();
        if ($type == 'hide') {
            $update_arr['snscomment_state'] = '1';
        }
        else {
            $update_arr['snscomment_state'] = '0';
        }
        $condition = array();
        $condition['snscomment_id'] = array('in',$cid_str);
        $result = $snscomment_model->editSnscomment($update_arr, $condition);
        if ($result>=0) {
            $this->log(lang('ds_edit').lang('admin_snstrace_pl'), 1);
            $this->success(lang('ds_common_op_succ'), 'snstrace/commentlist');
        }
        else {
            $this->error(lang('ds_common_op_fail'), 'snstrace/commentlist');
        }
    }

    protected function getAdminItemList()
    {
        $menu_array = array(
            array(
                'name' => 'index', 'text' => lang('admin_snstrace_tracelist'), 'url' => url('Snstrace/index')
            ), array(
                'name' => 'commentlist', 'text' => lang('admin_snstrace_commentlist'), 'url' => url('Snstrace/commentlist')
            ),
        );
        return $menu_array;
    }
}